#Exercício1
A=float(input("Insira um número"))
B=int(input("Insira um número inteiro"))
AB=(A/B)
print("A multiplicado por B é",A*B)
print("A dividido por B é",AB,"mas com duas casas decimais é %.2f" % AB)
print("A mais B é",A+B,"e A menos B é",A-B)
print("A elevado a B é",A**B)

#Exercício2
a=int(input("Digite o valor de a "))
b=int(input("Digite o valor de b "))
c=int(input("Digite o valor de c "))
Delta=(b**2 - 4*a*c)
soma=(-b+Delta**(1/2))
X1=(soma/2*a)
subtração=(-b-Delta**(1/2))
X2=(subtração/2*a)
a=str(a)
b=str(b)
c=str(c)
print(a+"X^2"+b+"X"+c+"=0")
print("a="+a+" b="+b+" c="+c)
print("X'=", X1,";","X''=",X2)